// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.1
// source: home/home.proto

package home

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Home struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HomeNum string `protobuf:"bytes,1,opt,name=home_num,json=homeNum,proto3" json:"home_num,omitempty"`
}

func (x *Home) Reset() {
	*x = Home{}
	if protoimpl.UnsafeEnabled {
		mi := &file_home_home_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Home) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Home) ProtoMessage() {}

func (x *Home) ProtoReflect() protoreflect.Message {
	mi := &file_home_home_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Home.ProtoReflect.Descriptor instead.
func (*Home) Descriptor() ([]byte, []int) {
	return file_home_home_proto_rawDescGZIP(), []int{0}
}

func (x *Home) GetHomeNum() string {
	if x != nil {
		return x.HomeNum
	}
	return ""
}

var File_home_home_proto protoreflect.FileDescriptor

var file_home_home_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x68, 0x6f, 0x6d, 0x65, 0x2f, 0x68, 0x6f, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x68, 0x6f, 0x6d, 0x65, 0x22, 0x21, 0x0a, 0x04, 0x48, 0x6f, 0x6d, 0x65, 0x12,
	0x19, 0x0a, 0x08, 0x68, 0x6f, 0x6d, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x68, 0x6f, 0x6d, 0x65, 0x4e, 0x75, 0x6d, 0x42, 0x13, 0x5a, 0x11, 0x67, 0x72,
	0x70, 0x63, 0x2f, 0x70, 0x62, 0x2f, 0x68, 0x6f, 0x6d, 0x65, 0x3b, 0x68, 0x6f, 0x6d, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_home_home_proto_rawDescOnce sync.Once
	file_home_home_proto_rawDescData = file_home_home_proto_rawDesc
)

func file_home_home_proto_rawDescGZIP() []byte {
	file_home_home_proto_rawDescOnce.Do(func() {
		file_home_home_proto_rawDescData = protoimpl.X.CompressGZIP(file_home_home_proto_rawDescData)
	})
	return file_home_home_proto_rawDescData
}

var file_home_home_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_home_home_proto_goTypes = []interface{}{
	(*Home)(nil), // 0: home.Home
}
var file_home_home_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_home_home_proto_init() }
func file_home_home_proto_init() {
	if File_home_home_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_home_home_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Home); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_home_home_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_home_home_proto_goTypes,
		DependencyIndexes: file_home_home_proto_depIdxs,
		MessageInfos:      file_home_home_proto_msgTypes,
	}.Build()
	File_home_home_proto = out.File
	file_home_home_proto_rawDesc = nil
	file_home_home_proto_goTypes = nil
	file_home_home_proto_depIdxs = nil
}
